// ─── MCP HTTP server (axum) ───────────────────────────────────────────────────
//
// Implements the Model Context Protocol JSON-RPC 2.0 server.
// Protocol version: 2024-11-05
//
// Endpoints:
//   POST /     → JSON-RPC 2.0 dispatch (all MCP methods)
//   GET  /health → {"status": "ok", "server": "loci-mcp", "version": "0.1.0"}
//
// Supported MCP methods:
//   initialize            → handshake, returns capabilities
//   resources/list        → lists all loci:// resources
//   resources/read        → reads a single resource by URI
//   resources/templates/list → lists URI templates
//   tools/list            → lists available tools
//   tools/call            → dispatches create_locus or tag_locus
//
// Cipher gate:
//   - Binds to 127.0.0.1:{port} only. Never 0.0.0.0.
//   - All responses include `X-Loci-Content-Trust: user-authored`.
//   - THREAT-01: no Conversation data in any response path.
//   - Port range enforced before bind: 1024–65535.
//   - Graceful shutdown via tokio oneshot channel.

use axum::{
    extract::State,
    http::{HeaderMap, HeaderValue, StatusCode},
    response::IntoResponse,
    routing::{get, post},
    Json, Router,
};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::net::SocketAddr;
use std::path::PathBuf;
use std::sync::Arc;
use tokio::net::TcpListener;
use tokio::sync::oneshot;

use super::resources;
use super::tools;

// ─── Server state ────────────────────────────────────────────────────────────

/// Shared state injected into every axum handler.
#[derive(Clone)]
pub struct McpServerState {
    /// Base path for the loci store (e.g. `~/.loci/`).
    pub loci_base: PathBuf,
    /// Room IDs exposed via MCP. Empty = all rooms exposed. Non-empty = allowlist.
    /// Enforced by resource handlers — agents can only read loci from listed rooms.
    /// Cipher gate: this value is set at server start and immutable for the server lifetime.
    pub expose_rooms: Vec<String>,
}

// ─── JSON-RPC types ───────────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
struct JsonRpcRequest {
    #[allow(dead_code)]
    jsonrpc: String,
    id: Option<Value>,
    method: String,
    #[serde(default)]
    params: Value,
}

#[derive(Debug, Serialize)]
struct JsonRpcResponse {
    jsonrpc: String,
    id: Option<Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    result: Option<Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    error: Option<JsonRpcError>,
}

#[derive(Debug, Serialize)]
struct JsonRpcError {
    code: i32,
    message: String,
}

impl JsonRpcResponse {
    fn ok(id: Option<Value>, result: Value) -> Self {
        Self { jsonrpc: "2.0".to_string(), id, result: Some(result), error: None }
    }

    fn err(id: Option<Value>, code: i32, message: impl Into<String>) -> Self {
        Self {
            jsonrpc: "2.0".to_string(),
            id,
            result: None,
            error: Some(JsonRpcError { code, message: message.into() }),
        }
    }
}

// ─── Cipher gate: security headers ───────────────────────────────────────────

/// Returns the security headers applied to every MCP response.
/// `X-Loci-Content-Trust: user-authored` signals to consuming agents that all
/// content in this response was authored by the user, not generated by an LLM.
/// This is the THREAT-01 attestation header.
fn loci_security_headers() -> HeaderMap {
    let mut headers = HeaderMap::new();
    headers.insert(
        "X-Loci-Content-Trust",
        HeaderValue::from_static("user-authored"),
    );
    headers.insert(
        "X-Loci-Threat-Gate",
        HeaderValue::from_static("THREAT-01:enforced"),
    );
    headers
}

// ─── MCP method handlers ──────────────────────────────────────────────────────

fn handle_initialize(id: Option<Value>) -> JsonRpcResponse {
    JsonRpcResponse::ok(
        id,
        json!({
            "protocolVersion": "2024-11-05",
            "capabilities": {
                "resources": {
                    "subscribe": false,
                    "listChanged": false
                },
                "tools": {}
            },
            "serverInfo": {
                "name": "loci-mcp",
                "version": "0.1.0",
                "description": "Loci knowledge garden — MCP server. Exposes user-authored Locus nodes for AI agent consumption."
            }
        }),
    )
}

fn handle_resources_list(id: Option<Value>, state: &McpServerState) -> JsonRpcResponse {
    let resources = resources::list_loci(&state.loci_base, &state.expose_rooms);
    JsonRpcResponse::ok(id, json!({ "resources": resources }))
}

fn handle_resources_templates_list(id: Option<Value>) -> JsonRpcResponse {
    JsonRpcResponse::ok(id, json!({
        "resourceTemplates": [
            {
                "uriTemplate": "loci://locus/{id}",
                "name": "Locus node by ID",
                "mimeType": "text/markdown",
                "description": "A single user-authored Locus node. Substitute {id} with the locus ID (e.g. locus-2026-05-09-sovereignty)."
            },
            {
                "uriTemplate": "loci://room/{roomId}/loci",
                "name": "All Loci in a Room",
                "mimeType": "application/json",
                "description": "Returns all Locus nodes belonging to the given Room. Substitute {roomId} with the room identifier."
            },
            {
                "uriTemplate": "loci://search?q={query}",
                "name": "Search Loci",
                "mimeType": "application/json",
                "description": "Keyword search over Locus titles and content. Returns up to 20 ranked results."
            }
        ]
    }))
}

fn handle_resources_read(id: Option<Value>, params: &Value, state: &McpServerState) -> JsonRpcResponse {
    let uri = match params.get("uri").and_then(|v| v.as_str()) {
        Some(u) => u,
        None => return JsonRpcResponse::err(id, -32602, "missing required param: uri"),
    };

    // Route by URI scheme
    if let Some(rest) = uri.strip_prefix("loci://locus/") {
        match resources::read_locus(rest, &state.loci_base, &state.expose_rooms) {
            Some(r) => JsonRpcResponse::ok(id, json!({
                "contents": [{
                    "uri": r.uri,
                    "mimeType": r.mime_type,
                    "text": r.text,
                    "metadata": r.metadata,
                }]
            })),
            None => JsonRpcResponse::err(id, -32002, format!("locus not found: {}", rest)),
        }
    } else if let Some(rest) = uri.strip_prefix("loci://room/") {
        // loci://room/{roomId}/loci
        let room_id = rest.trim_end_matches("/loci");
        // Cipher gate: check room is exposed before listing its loci
        if !state.expose_rooms.is_empty() && !state.expose_rooms.iter().any(|r| r == room_id) {
            return JsonRpcResponse::err(id, -32002, format!("room '{}' is not exposed via MCP", room_id));
        }
        let loci = resources::list_room_loci(room_id, &state.loci_base, &state.expose_rooms);
        let contents: Vec<Value> = loci
            .into_iter()
            .map(|r| json!({
                "uri": r.uri,
                "mimeType": r.mime_type,
                "text": r.text,
                "metadata": r.metadata,
            }))
            .collect();
        JsonRpcResponse::ok(id, json!({ "contents": contents }))
    } else if let Some(rest) = uri.strip_prefix("loci://search?q=") {
        let results = resources::search_loci(rest, &state.loci_base, &state.expose_rooms);
        let contents: Vec<Value> = results
            .into_iter()
            .map(|r| json!({
                "uri": r.uri,
                "mimeType": r.mime_type,
                "text": r.text,
                "metadata": r.metadata,
            }))
            .collect();
        JsonRpcResponse::ok(id, json!({ "contents": contents }))
    } else {
        JsonRpcResponse::err(id, -32002, format!("unknown loci URI scheme: {}", uri))
    }
}

fn handle_tools_list(id: Option<Value>) -> JsonRpcResponse {
    JsonRpcResponse::ok(id, json!({
        "tools": [
            {
                "name": "create_locus",
                "description": "Create a new Locus node in the knowledge garden. The node is written to ~/.loci/loci/ as a Markdown file with YAML frontmatter.",
                "inputSchema": {
                    "type": "object",
                    "properties": {
                        "title": {
                            "type": "string",
                            "description": "The title of the new Locus node."
                        },
                        "content": {
                            "type": "string",
                            "description": "Markdown body content for the Locus."
                        },
                        "tags": {
                            "type": "array",
                            "items": { "type": "string" },
                            "description": "Optional tags to categorise the Locus."
                        },
                        "room_id": {
                            "type": "string",
                            "description": "Optional Room ID to assign this Locus to."
                        }
                    },
                    "required": ["title", "content"]
                }
            },
            {
                "name": "tag_locus",
                "description": "Update the tags on an existing Locus node. Replaces the existing tag list with the provided tags.",
                "inputSchema": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string",
                            "description": "The Locus ID (e.g. locus-2026-05-09-sovereignty)."
                        },
                        "tags": {
                            "type": "array",
                            "items": { "type": "string" },
                            "description": "New tag list (replaces existing)."
                        }
                    },
                    "required": ["id", "tags"]
                }
            }
        ]
    }))
}

fn handle_tools_call(id: Option<Value>, params: &Value, state: &McpServerState) -> JsonRpcResponse {
    let name = match params.get("name").and_then(|v| v.as_str()) {
        Some(n) => n,
        None => return JsonRpcResponse::err(id, -32602, "missing required param: name"),
    };
    let args = params.get("arguments").unwrap_or(&Value::Null);

    match name {
        "create_locus" => {
            let title = match args.get("title").and_then(|v| v.as_str()) {
                Some(t) => t,
                None => return JsonRpcResponse::err(id, -32602, "create_locus: missing required argument: title"),
            };
            let content = match args.get("content").and_then(|v| v.as_str()) {
                Some(c) => c,
                None => return JsonRpcResponse::err(id, -32602, "create_locus: missing required argument: content"),
            };
            let tags: Vec<String> = args
                .get("tags")
                .and_then(|v| v.as_array())
                .map(|a| a.iter().filter_map(|t| t.as_str().map(|s| s.to_string())).collect())
                .unwrap_or_default();
            let room_id = args.get("room_id").and_then(|v| v.as_str());

            match tools::create_locus(title, content, &tags, room_id, &state.loci_base) {
                Ok(uri) => JsonRpcResponse::ok(id, json!({
                    "content": [{
                        "type": "text",
                        "text": format!("Created: {}", uri)
                    }]
                })),
                Err(e) => JsonRpcResponse::err(id, -32000, format!("create_locus failed: {}", e)),
            }
        }

        "tag_locus" => {
            let locus_id = match args.get("id").and_then(|v| v.as_str()) {
                Some(i) => i,
                None => return JsonRpcResponse::err(id, -32602, "tag_locus: missing required argument: id"),
            };
            let tags: Vec<String> = match args.get("tags").and_then(|v| v.as_array()) {
                Some(a) => a.iter().filter_map(|t| t.as_str().map(|s| s.to_string())).collect(),
                None => return JsonRpcResponse::err(id, -32602, "tag_locus: missing required argument: tags"),
            };

            match tools::tag_locus(locus_id, &tags, &state.loci_base) {
                Ok(()) => JsonRpcResponse::ok(id, json!({
                    "content": [{
                        "type": "text",
                        "text": format!("Tags updated on locus '{}'", locus_id)
                    }]
                })),
                Err(e) => JsonRpcResponse::err(id, -32000, format!("tag_locus failed: {}", e)),
            }
        }

        other => JsonRpcResponse::err(id, -32601, format!("unknown tool: {}", other)),
    }
}

// ─── axum handler ────────────────────────────────────────────────────────────

async fn mcp_rpc(
    State(state): State<Arc<McpServerState>>,
    Json(request): Json<JsonRpcRequest>,
) -> impl IntoResponse {
    let id = request.id.clone();

    let response = match request.method.as_str() {
        "initialize" => handle_initialize(id),
        "resources/list" => handle_resources_list(id, &state),
        "resources/read" => handle_resources_read(id, &request.params, &state),
        "resources/templates/list" => handle_resources_templates_list(id),
        "tools/list" => handle_tools_list(id),
        "tools/call" => handle_tools_call(id, &request.params, &state),
        // Notifications (no response required by MCP spec, but we ack)
        "notifications/initialized" => return (loci_security_headers(), StatusCode::NO_CONTENT).into_response(),
        other => JsonRpcResponse::err(id, -32601, format!("method not found: {}", other)),
    };

    (loci_security_headers(), Json(response)).into_response()
}

async fn health_check() -> impl IntoResponse {
    (
        loci_security_headers(),
        Json(json!({
            "status": "ok",
            "server": "loci-mcp",
            "version": "0.1.0",
            "protocol": "2024-11-05",
            "threat_gate": "THREAT-01:enforced"
        })),
    )
}

// ─── Public: server lifecycle ─────────────────────────────────────────────────

/// Start the MCP server on `localhost:{port}`.
/// Returns the actual bound port (useful when port=0 for OS assignment).
/// The server runs until `shutdown_rx` fires.
pub async fn start_server(
    port: u16,
    loci_base: PathBuf,
    expose_rooms: Vec<String>,
    shutdown_rx: oneshot::Receiver<()>,
) -> Result<u16, String> {
    let state = Arc::new(McpServerState { loci_base, expose_rooms });

    let app = Router::new()
        .route("/", post(mcp_rpc))
        .route("/health", get(health_check))
        .with_state(state);

    // Bind to 127.0.0.1 only — Cipher gate, non-negotiable.
    let addr = SocketAddr::from(([127, 0, 0, 1], port));
    let listener = TcpListener::bind(addr)
        .await
        .map_err(|e| format!("failed to bind MCP server to {}: {}", addr, e))?;

    let actual_port = listener
        .local_addr()
        .map(|a| a.port())
        .map_err(|e| e.to_string())?;

    tokio::spawn(async move {
        axum::serve(listener, app)
            .with_graceful_shutdown(async { let _ = shutdown_rx.await; })
            .await
            .ok();
    });

    Ok(actual_port)
}
